# Generated by Django 5.2.12 on 2026-03-27 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_wtr_pages', '0003_alter_contentpage_body_alter_indexpage_body'),
        ('wagtail_wtr_wtrx', '0002_alter_integrationsettings_action_network_api_key'),
        ('wagtailmedia', '0005_alter_media_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='hero_video',
            field=models.ForeignKey(blank=True, help_text='Optional video displayed in the hero. When set, the layout switches to two columns: text on the left, video on the right. Upload a thumbnail on the video in the media library to use as a poster frame; falls back to the hero image above if no thumbnail is set.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailmedia.media', verbose_name='hero video'),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='hero_video',
            field=models.ForeignKey(blank=True, help_text='Optional video displayed in the hero. When set, the layout switches to two columns: text on the left, video on the right. Upload a thumbnail on the video in the media library to use as a poster frame; falls back to the hero image above if no thumbnail is set.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailmedia.media', verbose_name='hero video'),
        ),
        migrations.AlterField(
            model_name='contentpage',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text='Optional hero background or feature image. Also used as the video poster if no thumbnail is set on the video.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtail_wtr_wtrx.customimage', verbose_name='hero image'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text='Optional hero background or feature image. Also used as the video poster if no thumbnail is set on the video.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtail_wtr_wtrx.customimage', verbose_name='hero image'),
        ),
    ]
