# Generated by Django 5.2.12 on 2026-03-27 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_wtr_home', '0004_homepage_hero_video_alter_homepage_hero_image'),
        ('wagtailmedia', '0005_alter_media_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero_video',
            field=models.ForeignKey(blank=True, help_text='Optional video displayed in the hero. When set, the layout switches to two columns: text on the left, video on the right. Upload a thumbnail on the video in the media library to use as a poster frame; falls back to the hero image above if no thumbnail is set.', limit_choices_to={'type': 'video'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailmedia.media', verbose_name='hero video'),
        ),
    ]
